### ISSUE TITLE
ProxSDP does not return same solution as Mosek, is ProxSDP guaranteed to solve an SDP?

### ISSUE THREAD

**Issue by hankyang94** [mariohsouto/ProxSDP.jl#18]
I was trying ProxSDP in solving a convex SDP whose solution rank is 1, my optimization is:
min (trace(QZ))
subject to: some equality constraints on entries of Z.
Where Q is a given cost matrix and Z is my PSD decision variable.

This optimization gives rank 1 solution in CVX using SeDuMi (Matlab), and also gives rank 1 solution in Julia using Mosek solver. 

However, ProxSDP does not give rank 1 solution, and the resulting Z^* is incorrect, although I did notice that ProxSDP is much faster than Mosek.

So I am wondering, is ProxSDP guaranteed to find the optimal solution of an SDP? (Just like conventional Interior Points Methods)?

**Comment by mariohsouto** [comment]
Hi,

ProxSDP is guaranteed to return the optimal solution. This issue is either
a bug or the tolerance needs to be smaller. Since the solver is rather new
there might be something odd happening. Can you provide the problem you are
trying to solve?


Em Seg, 11 de mar de 2019 11:29, hankyang94 <notifications@github.com>
escreveu:

**Comment by hankyang94** [comment]
Below is my Julia code:
```
using ProxSDP, JuMP, LinearAlgebra, MAT
using Mosek, MosekTools

# read the cost matrix from matlab file
# file = matopen("/Users/hankyang/Documents/MATLAB/vectorRegistration/Q_cost_50pt.mat")
# file = matopen("/Users/hankyang/Documents/MATLAB/vectorRegistration/Q_cost_100pt_50Outlier.mat")
# file = matopen("/Users/hankyang/Documents/MATLAB/vectorRegistration/Q_cost_10pt_5Outlier.mat")
file = matopen("/Users/hankyang/Documents/MATLAB/vectorRegistration/Q_cost_10pt_1Outlier.mat")

Q_cost=read(file, "Q_cost")
close(file)
println("Finished reading Q_cost")
# recover number of points
nrPts=Int( (size(Q_cost,1)-4)/4 )
Npm=Int( 4*nrPts+4 )

# create JuMP Model
# model = Model(with_optimizer(ProxSDP.Solver, log_verbose=true))
model = Model(with_optimizer(Mosek.Optimizer))

# create decision variable
@variable(model, X[1:Npm,1:Npm], PSD)

# qqTran=X[1:4,1:4]

# define objective value
@objective(model, Min, tr(Q_cost*X))

# add constraints
@constraint(model,tr(X[1:4,1:4])==1.0)
println("Adding diagonal block equality constraints")
for k=1:nrPts
    @constraint(model,X[(4*k+1):(4*k+4),(4*k+1):(4*k+4)].==X[1:4,1:4])
end
println("Adding off-diagonal block symmetry constraints")
for k1=0:nrPts
    for k2=(k1+1):nrPts
        @constraint(model,X[(4*k1+1):(4*k1+4),(4*k2+1):(4*k2+4)].==transpose( X[(4*k1+1):(4*k1+4),(4*k2+1):(4*k2+4)] ) )
    end
end

# Then we can solve the model
println("Start solving")
JuMP.optimize!(model)
if termination_status(model) == MOI.OPTIMAL
    optimal_solution = value.(X)
    optimal_objective = objective_value(model)
elseif termination_status(model) == MOI.TIME_LIMIT && has_values(model)
    suboptimal_solution = value.(X)
    suboptimal_objective = objective_value(model)
else
    error("The model was not solved correctly.")
end
```
Notice that at line 18 and 19, I was switching between Mosek and ProxSDP. (Mosek gave me the correct solution but ProxSDP did not).

The cost matrix `Q_cost` is a Matlab file, which you can download through this [link:](https://www.dropbox.com/s/p0hi3z6cp2nll8r/Q_cost_10pt_1Outlier.mat?dl=0).

Let me know, I am hoping this is just a tolerance issue.

**Comment by guilhermebodin** [comment]
Hi @hankyang94 

I tried 
`model = Model(with_optimizer(ProxSDP.Solver, log_verbose=true, tol_primal = 1e-5, tol_dual = 1e-5))`
default values are `tol_primal = 1e-4` and `tol_dual = 1e-4`

It returned the same answer of Mosek until the 5th decimal place. It also returned the same objective value until the 6th decimal place.

Please let us know if this works for you

**Comment by hankyang94** [comment]
Thanks, it works. However, I don't see much gain over Mosek in terms of timing. 

I tried solving with PSD variable 204 by 204, and I saw most of time, ProxSDP was solving at rank 204 (full rank), which makes it consume similar time compared with Mosek. Although the correct solution rank should still have rank 1.

**Comment by joaquimg** [comment]
We will look into this. It probably can be improved.
What is the timming difference?

The problem you mentioned is the one you provided data?

**Comment by hankyang94** [comment]
The datafiles I used can be found through this [link](https://www.dropbox.com/sh/unrhg5cs55zdh91/AACnUBJgR1isqQZl_N5cMlm3a?dl=0), same problem formulation, just the PSD variable has much larger size. (Q_cost_50pt will have size 204by204 and Q_cost_100pts will have size 404 by 404).
