### ISSUE TITLE
SDP set

### ISSUE THREAD

**Issue by blegat** [mariohsouto/ProxSDP.jl#38]
From the MOI wrapper, I see that you are transforming the PSD set from "upper triangular column-wise" (the MOI definition) to "lower triangular column-wise" (the SCS definition). Is there any reason not to use the MOI definition ?
As noted [here](http://www.juliaopt.org/MathOptInterface.jl/v0.8/apireference/#MathOptInterface.PositiveSemidefiniteConeTriangle):

> The advantage of the first format is the mapping between the (i, j) matrix indices and the k index of the vectorized form. It is simpler and does not depend on the side dimension of the matrix.

so there is a small advantage for the MOI version but I see no advantage for the SCS one.

**Comment by mariohsouto** [comment]
There is no particular reason for using the column-wise transformation. I believe this is the default for Julia, "Multidimensional arrays in Julia are stored in column-major order.". In the Julia documentation they argue that a column-wise transformation would be more efficient, see https://docs.julialang.org/en/latest/manual/performance-tips/ . Is there any reason this would be the opposite for MOI?

**Comment by blegat** [comment]
We do column-wise too but it is upper triangular instead of lower triangular

**Comment by mariohsouto** [comment]
I see, we can change from lower to upper triangular.

**Comment by blegat** [comment]
I just noticed the mistake in my initial post, the SCS format is "lower triangular column-wise", not "lower triangular row-wise". I have corrected it

**Comment by joaquimg** [comment]
Now its upper triangular. see #58
