### ISSUE TITLE
high precision?

### ISSUE THREAD

**Issue by ericphanson** [mariohsouto/ProxSDP.jl#42]
I was wondering if as a pure-Julia SDP solver, would it be possible to use something like `BigFloat`'s with `ProxSDP.jl`? I know JuMP automatically converts inputs to `Float64` but I thought maybe it would be possible to use the library directly without going through JuMP. I thought I would ask first if it were possible first, before spending too much time on it though. I understand it would surely be slow, but there are some quite small SDPs that it would still be interesting to me to check some things at high precision.

**Comment by blegat** [comment]
> I thought maybe it would be possible to use the library directly without going through JuMP

If you use MathOptInterface (MOI), you can use use other arithmetic than Float64. That is the reason I use MOI and not JuMP [here](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/8a0d39a1bc8610530e999b29d8acdfa0db17ead8/src/opt.jl#L89-L133) in Polyhedra.

**Comment by ericphanson** [comment]
Ah, thanks! That sounds promising. 

I started looking through the ProxSDP codebase though, and it seems like at least a few changes would be needed: the `eigs!` function would need to use e.g. GenericLinearAlgebra.jl instead of Arpack in the general case, the explicit `LinearAlgebra.BLAS.gemm!` calls would need to be replaced, and the functions `Vector{Float64}` in the `prox_operators.jl` file would need to be more generically typed than `Vector{Float64}`.

**Comment by joaquimg** [comment]
We used so far Float64 to get rid of some type instabilities easily.
But using BigFloats is a long (maybe medium) term plan.
PRs are very welcome!

**Comment by joaquimg** [comment]
And ProxSDP works directly with MOI so you dont need to worry about JuMP, you can use MOI.

**Comment by mariohsouto** [comment]
This is a very interesting topic. It is technically possible to make ProxSDP work with BigFloat. However, I don't think any first order method would be suitable for this. Maybe implementing some a pure Julia solution refinement method like https://arxiv.org/pdf/1811.02157.pdf should be done on top of ProxSDP.

**Comment by ericphanson** [comment]
That paper looks really interesting. It seems like such a refinement step could possibly refine solutions from even non-pure-Julia solvers to high precision since it only needs an approximate solution to start with.

**Comment by mariohsouto** [comment]
Unfortunately, we don't provide the residual map.

**Comment by ericphanson** [comment]
Ok, thanks for letting me know. 

This is a bit off-topic to ProxSDP, but I'll (likely) be co-supervising an undergraduate summer student for a 2-month project starting mid-July whose general topic is high-precision SDPs. Our plan is to first set up a Julia interface (and binary builder) for SDPA-GMP, and then look into refinement methods and other ideas as time permits. So I'm interested in any developments or ideas on this front!

(Feel free to close the issue though, or consider it an open feature request).

**Comment by mariohsouto** [comment]
I believe it would be very useful to have a refinement method implemented in Julia. Keep us informed about your progress. I would be happy to contribute.
