### ISSUE TITLE
Test failures from Convex.jl tests

### ISSUE THREAD

**Issue by ericphanson** [mariohsouto/ProxSDP.jl#64]
See here: https://ericphanson.github.io/ConvexTests.jl/dev/ProxSDP.html (and see [here](https://discourse.julialang.org/t/ann-convex-0-13-released/35304/2) for a discourse post introducing that repo, ConvexTests.jl). Some of the failures might just be settings and things like that; e.g., with COSMO [most of the failures were max-iteration related](https://github.com/ericphanson/ConvexTests.jl/pull/1), but it would be great to figure out what settings can solve a variety of problems to `1e-3`, and it's possible the tests are surfacing bugs as well.

**Comment by mariohsouto** [comment]
Hi @ericphanson, I'm sorry for the late reply on this issue. The link you posted seems to be expired can you update it so I can take a look?

**Comment by ericphanson** [comment]
Oops, sorry, the link is https://ericphanson.github.io/ConvexTests.jl/dev/ProxSDP/ (no .html). Those tests were run with ProxSDP 1.3.1 (all the version information is at the end of the page). You can look at the repo for the code to run the tests: https://github.com/ericphanson/ConvexTests.jl

**Comment by joaquimg** [comment]
Hi @ericphanson,
I am figuring out a reasonable set of parameters.
Some problems might take some time to converge, so my question is what would be your overall upper bound on execution time?

**Comment by ericphanson** [comment]
Hi, good question. For https://ericphanson.github.io/ConvexTests.jl/dev/SDPA_GMP/#SDPA_GMP-presolvetrue I excluded a few problems with > 15 minute presolve time; afterwards the whole tests run in a few minutes. Let's say a maximum of 30 minutes total time, but problems that are really long for whatever reason can be excluded to hit that run time.

I think ideally we would modify the tests so that reporting something like `MOI.ITERATION_LIMIT` and then not hitting the tolerance target would be OK too (or perhaps there could be multiple categories or subdivisions etc), but that would take a lot of work still (there are many tests to update).

**Comment by joaquimg** [comment]
Thanks! I will set proper parameters and send you.

**Comment by ericphanson** [comment]
Ok great! If you make a PR to modify to change this line https://github.com/ericphanson/ConvexTests.jl/blob/a4c02dca1c42558144c72d7a25afd365a4dc9a81/ProxSDP/test.jl#L4 then I'll merge it which will trigger the runs and docs update and we can see how it goes, and make more PRs as needed. (We don't have any kind of staging setup etc, so that's the current process).

**Comment by mariohsouto** [comment]
Changes are reflected at https://ericphanson.github.io/ConvexTests.jl/dev/ProxSDP/ . Thanks @ericphanson for providing this feedback. We were able to improve the solver based on the tests you have put together. I'm closing the issue for now.
