### ISSUE TITLE
Does ProxSDP assume decomposition of X...?

### ISSUE THREAD

**Issue by bcdandurand** [mariohsouto/ProxSDP.jl#65]
That is, instead of assuming one PSD constraint `X in PSDCone()`, we can have `X_1 in PSDCone()`, `X_2 in PSDCone()`, etc. Is this how ProxSDP is implemented? Or does it assume one matrix block `X in PSDCone()`?

I expect this question to be related to the issue: 
[Chordal decomposition issue](https://github.com/mariohsouto/ProxSDP.jl/issues/21)

**Comment by bcdandurand** [comment]
If I understand the code in `MOI_wrapper.jl` correctly, the possibility of having more than one conic constraint (linear, SOC, and SDP) is allowed for.

**Comment by mariohsouto** [comment]
Yes, you can have multiple p.s.d. variables in your formulation. So if you have some way to decompose your problem into multiple smaller p.s.d. cones you should try it out.
